version: '2'
services:
  web:
    build: .
    image: georgianbudgetpublic
    volumes:
      - .:/myapp
      - /myapp/node_modules
    command: /bin/sh -c 'npm run start'
    ports:
      - "8080:8080"
